### ISSUE TITLE
Module for users

### ISSUE THREAD

**Issue by testt23** [luyadev/luya-module-account#2]
Hey, dude and ladies, would it be useful for us to have a module for registration, login, change, logout for users, and access rights (created through db)?

I think it would help us. If you do not think it's necessary, what do you use then?

**Comment by testt23** [comment]
I would like to pay for a module, 
but as long as it meets the following requirements:
- login, exit, registration, profile change (password, names)
- subscription-based payment option (managed administration panel plans)
- sign up against a $ 10 credit card transfer
- Discussion between users
- the ability to block a user

how much would it cost me?

**Comment by nadar** [comment]
If we would build a user module this would be part of `login, exit, registration, profile change (password, names)` and `the ability to block a user` the rest will not as its to specific task.

**Comment by testt23** [comment]
Ok. How much would it cost me(30,40,70€?), and I buy from you?

**Comment by nadar** [comment]
Issues are not made to talke about business opportunities, here we can talk about what the account module should contain. If you want a real offer you can contact us info@zephir.ch, but your pricing is not realistic at all.
